name: Windows 11 trên GitHub Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Đang tải các gói cần thiết
      run: |
        sudo apt update
        sudo apt install qemu-kvm -y
        qemu-img create -f raw filegz.img 20G
        wget -O- --no-check-certificate http://drive.muavps.net/windows/windows11iot.gz | gunzip | dd of=filegz.img
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install ngrok -y
    - name: Đang thêm token Ngrok
      run: |
        ngrok authtoken 2baUJjx8LzwD6Cx0NAoqIqAbQEf_7KUC2okYkowAjvRUYJyTh
        ngrok tcp 3389 &>/dev/null &
    - name: Thêm ổ đĩa
      run: |
        sudo qemu-img resize filegz.img 1025G
    - name: Chạy QEMU
      run: |
        sudo qemu-system-x86_64 \
        -net nic -net user,hostfwd=tcp::3389-:3389 \
        -m 12G -smp cores=4 \
        -cpu max \
        -enable-kvm \
        -boot order=d \
        -drive file=filegz.img,format=raw,if=virtio \
        -device usb-ehci,id=usb,bus=pci.0,addr=0x4 \
        -device usb-tablet \
        -vnc :0 -vga virtio
